<a href="https://colab.research.google.com/github/SaranyaMulagani/6months-fsds-genai-agenticai/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
type(np)

module

In [3]:
np.__version__

'2.0.2'

In [4]:
import sys

In [5]:
sys.version

'3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]'

In [6]:
my_list=[0,1,2,3,4,5]

In [7]:
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

In [9]:
arr=np.array(my_list)

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(10,25,3)

array([10, 13, 16, 19, 22])

In [16]:
np.arange(20,8)

array([], dtype=int64)

In [18]:
np.arange(-2,18,3)

array([-2,  1,  4,  7, 10, 13, 16])

In [19]:
np.arange(1,20,3,5)

TypeError: Cannot interpret '5' as a data type

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(3 ,dtype=int)

array([0, 0, 0])

In [23]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
nd=np.zeros((5,9),dtype = int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [28]:
nd1 =np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.t

In [1]:
import numpy as np
np.random.rand(2)

array([0.89617083, 0.84195229])

In [11]:
np.random.randint(4) # prints from 1 to 3 except 4

1

In [23]:
np.random.randint(2,10)#2 is inclusive 10 exclusive

4

In [27]:
np.random.randint(2,10,2) #generates 2 random numbers between 2 to 10 , 10 is exclusive

array([2, 8])

In [28]:
np.random.randint(2,10,4) #generates 4 random numbers bw 2 to 10 , 10 iis exclusive

array([9, 5, 5, 4])

In [30]:
np.random.randint(10,40,(10,10)) # generates 10*10 matrix

array([[25, 38, 38, 33, 12, 14, 19, 30, 26, 16],
       [31, 36, 37, 33, 38, 28, 12, 23, 35, 34],
       [19, 26, 27, 28, 25, 24, 14, 26, 37, 30],
       [19, 29, 17, 25, 39, 30, 31, 27, 23, 11],
       [39, 23, 37, 28, 35, 18, 13, 28, 23, 32],
       [30, 20, 29, 16, 15, 20, 28, 24, 24, 22],
       [28, 34, 12, 26, 32, 37, 37, 20, 30, 35],
       [21, 33, 35, 20, 35, 26, 27, 34, 21, 37],
       [35, 34, 19, 26, 18, 18, 17, 31, 24, 30],
       [29, 31, 18, 34, 33, 33, 34, 18, 22, 23]])

In [31]:
m=np.random.randint(10,40,(10,10)) # generates 10*10 matrix

In [32]:
m

array([[14, 31, 24, 31, 24, 29, 16, 30, 15, 34],
       [31, 38, 19, 27, 35, 31, 27, 14, 17, 24],
       [31, 20, 24, 16, 12, 22, 29, 39, 18, 26],
       [33, 38, 14, 38, 28, 39, 28, 26, 30, 29],
       [29, 18, 38, 36, 28, 36, 28, 24, 12, 30],
       [38, 33, 25, 30, 29, 20, 24, 20, 17, 28],
       [35, 33, 35, 14, 28, 30, 21, 10, 26, 36],
       [14, 19, 12, 35, 25, 34, 23, 33, 39, 29],
       [19, 32, 12, 38, 10, 18, 15, 36, 12, 13],
       [15, 30, 34, 23, 27, 21, 30, 33, 23, 35]])

In [38]:
arr=np.array([1,2,3,4,5,6])

In [39]:
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [43]:
m

array([[14, 31, 24, 31, 24, 29, 16, 30, 15, 34],
       [31, 38, 19, 27, 35, 31, 27, 14, 17, 24],
       [31, 20, 24, 16, 12, 22, 29, 39, 18, 26],
       [33, 38, 14, 38, 28, 39, 28, 26, 30, 29],
       [29, 18, 38, 36, 28, 36, 28, 24, 12, 30],
       [38, 33, 25, 30, 29, 20, 24, 20, 17, 28],
       [35, 33, 35, 14, 28, 30, 21, 10, 26, 36],
       [14, 19, 12, 35, 25, 34, 23, 33, 39, 29],
       [19, 32, 12, 38, 10, 18, 15, 36, 12, 13],
       [15, 30, 34, 23, 27, 21, 30, 33, 23, 35]])

In [44]:
b=np.random.randint(10,20,(5,4))
b

array([[16, 18, 17, 11],
       [13, 15, 17, 17],
       [13, 16, 12, 14],
       [10, 19, 17, 16],
       [14, 13, 12, 12]])

In [45]:
b[:]

array([[16, 18, 17, 11],
       [13, 15, 17, 17],
       [13, 16, 12, 14],
       [10, 19, 17, 16],
       [14, 13, 12, 12]])

In [46]:
b[1:4] # gets 1,2,3 rows

array([[13, 15, 17, 17],
       [13, 16, 12, 14],
       [10, 19, 17, 16]])

In [47]:
b[-1:]

array([[14, 13, 12, 12]])

In [48]:
b[:-1]

array([[16, 18, 17, 11],
       [13, 15, 17, 17],
       [13, 16, 12, 14],
       [10, 19, 17, 16]])

In [49]:
b[:-2]

array([[16, 18, 17, 11],
       [13, 15, 17, 17],
       [13, 16, 12, 14]])

In [50]:
b[1:4]

array([[13, 15, 17, 17],
       [13, 16, 12, 14],
       [10, 19, 17, 16]])

In [53]:
b[1,-1]

np.int64(17)

In [51]:
b[1,2]

np.int64(17)

In [52]:
b[1,3]

np.int64(17)

In [54]:
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
arr.max()

np.int64(6)

In [56]:
mat = np.random.randint(0,100,(10,10))
mat

array([[95, 38, 32, 92, 53, 49, 54, 49, 67, 54],
       [28, 87, 65, 59, 97, 30, 93, 18, 32, 86],
       [53, 48, 41, 54, 54,  0,  2, 85, 65, 14],
       [67, 71, 59, 29, 85,  2, 70, 62, 36, 57],
       [67, 51, 33, 18, 44, 88, 64, 89, 87, 62],
       [64, 72,  8, 77, 70, 48, 77, 62, 94, 25],
       [10, 41, 49, 57, 79, 25, 99, 19, 14, 68],
       [11, 85, 40, 56, 20, 78, 35,  4, 53, 93],
       [61,  2, 28, 98, 36, 49, 33, 64, 17, 87],
       [75, 52, 11, 78,  3, 78, 45, 91, 46,  7]])

In [59]:
row=6
col=4

In [60]:
mat[row,col]

np.int64(79)

In [61]:
mat[1]

array([28, 87, 65, 59, 97, 30, 93, 18, 32, 86])

In [62]:
mat[:,col]

array([53, 97, 54, 85, 44, 70, 79, 20, 36,  3])

In [63]:
mat[::-1]

array([[75, 52, 11, 78,  3, 78, 45, 91, 46,  7],
       [61,  2, 28, 98, 36, 49, 33, 64, 17, 87],
       [11, 85, 40, 56, 20, 78, 35,  4, 53, 93],
       [10, 41, 49, 57, 79, 25, 99, 19, 14, 68],
       [64, 72,  8, 77, 70, 48, 77, 62, 94, 25],
       [67, 51, 33, 18, 44, 88, 64, 89, 87, 62],
       [67, 71, 59, 29, 85,  2, 70, 62, 36, 57],
       [53, 48, 41, 54, 54,  0,  2, 85, 65, 14],
       [28, 87, 65, 59, 97, 30, 93, 18, 32, 86],
       [95, 38, 32, 92, 53, 49, 54, 49, 67, 54]])

In [64]:
mat[::-2]

array([[75, 52, 11, 78,  3, 78, 45, 91, 46,  7],
       [11, 85, 40, 56, 20, 78, 35,  4, 53, 93],
       [64, 72,  8, 77, 70, 48, 77, 62, 94, 25],
       [67, 71, 59, 29, 85,  2, 70, 62, 36, 57],
       [28, 87, 65, 59, 97, 30, 93, 18, 32, 86]])

In [65]:
mat[1:2,2:4]

array([[65, 59]])

In [66]:
mat>40

array([[ True, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True, False,  True, False, False,
         True],
       [ True,  True,  True,  True,  True, False, False,  True,  True,
        False],
       [ True,  True,  True, False,  True, False,  True,  True, False,
         True],
       [ True,  True, False, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
        False],
       [False,  True,  True,  True,  True, False,  True, False, False,
         True],
       [False,  True, False,  True, False,  True, False, False,  True,
         True],
       [ True, False, False,  True, False,  True, False,  True, False,
         True],
       [ True,  True, False,  True, False,  True,  True,  True,  True,
        False]])