<a href="https://colab.research.google.com/github/SaranyaMulagani/6months-fsds-genai-agenticai/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
type(np)

module

In [3]:
np.__version__

'2.0.2'

In [4]:
import sys

In [5]:
sys.version

'3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]'

In [6]:
my_list=[0,1,2,3,4,5]

In [7]:
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

In [9]:
arr=np.array(my_list)

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(10,25,3)

array([10, 13, 16, 19, 22])

In [16]:
np.arange(20,8)

array([], dtype=int64)

In [18]:
np.arange(-2,18,3)

array([-2,  1,  4,  7, 10, 13, 16])

In [19]:
np.arange(1,20,3,5)

TypeError: Cannot interpret '5' as a data type

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(3 ,dtype=int)

array([0, 0, 0])

In [23]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
nd=np.zeros((5,9),dtype = int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [28]:
nd1 =np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.t